#!/bin/bash
clear
sleep 0,020;echo "                                                                                                                                                                                                                                                                                                                                                                                                                                                                " | pv -qL 420
sleep 0,020;echo "                                                                                                                                                                                                                                                                                                                                                                                                                                                                " | pv -qL 420
sleep 0,020;echo "                                                                                                                                                                                                                                                                                                                                                                                                                                                                " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                                                                                                                                                                                                                                                                                                                " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                                                           .....',,''',;,,:;::::;;;,,,'.                                                                                                                                                                                                                        " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                                                   .....,;:ccclcc::::cc:::::c:::::cccclodl:.                                                                                                                                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                                            .',;cloolc:cc::ccccc:::cccccccc:::::::cccccclloddc;'                                                                                                                                                                                                                " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                                      ..';;:c:ccclllc:ccccclllccccccccccccc::ccccccc:cccclcllloooc,                                                                                                                                                                                                             " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                                  .,:cccccc:::cllllcccllllllllllllllllllcclclllcccccccccccclllccllloc;                                                                                                                                                                                                          " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                             ..,;cc::::ccccccllooolllllllolllloolllllllllllloollllcccccccllllcccccclodd,                                                                                                                                                                                                        " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                          'clc:::::::cclllcllloooooooooooollllooloooooooooooooolllllllllllllccccccclllodxc                                                                                                                                                                                                      " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                      ..,;ccc::::ccccllllllloooddooooooooooooooooddooddodddddoooooooooooooollllllllllllloddc'                                                                                                                                                                                                   " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                    'cc::cllc:ccclllllooooooddddddoodddddoooodddddddddddddddddddxddddodddddooooooooooolllooodkc                                                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                 .;llccc:lollclllllooooooooodxxxdddoddddddoodddddddddddxxddddxxxxxxddxxxxxxxxxxxxxxdddoooooodddkd.                                                                                                                                                                                              " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                :olc:clllllllloollllooddododdxxxddddxxxdddodddxxdxxxxxxxxxxxxxxkxkkkkkkkkkkkOOOOkkxxxxddddoooooodko.                                                                                                                                                                                            " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                              .:lccccllllllolloooolooddxddddxxxxxdddxxxxddddxxxxxxxxxkkkkkkkkkkkkOOOOOO00OOOOOOOOkkkxxxdddoooooooodOd.                                                                                                                                                                                          " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                            .cccclllllolllloooooooooodxxxxddxxxxxdddxxxxdddxxxkkkkkkkOOkOOOOkkkOOO00000KK0000000OOkkkkxxxddddooooddddxo                                                                                                                                                                                         " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                          .:loolllloooodooooooodddddddxxxxxxxxkkxxxxxxxxxxxxkkkOOOOOOOOOOOOOOOOO00000KKKKKK000000OOOkkkkxxxddddooooooodx.                                                                                                                                                                                       " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                        .;cllloooodddxxxdddooddddxxdddxxxxxxxxkkkxxxxkkkkkkkkkOO00000000000OOO0000000KKKKKKK000000OOOOkkkkkxxxdddoooooookd                                                                                                                                                                                      " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                       'cclllooddxxxkkkkkxxxxxxdxxxxxxxxkkkkkkkkkkkkkkkkkkkkkOO000000000000000000000000KKKKK00000OOOOOOkkkkxxxdoolllllllodd                                                                                                                                                                                     " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                      ,:cclloodxxxkkkOOOOkkkkkxxxxxxkkkkkkkkkkOOOkkkkOOkkOOOO000000000000000000000000000000000000OOOOOOkkkkxxxddolllllllood.                                                                                                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                     ,:ccclooddxxxkkkOOOOOOOOkkkkxxkkkkkkkkkkkOOOOkkkOOOOOO000000000000000000000000000000000000000OOOOOOkkkkxxxddoooooolllox                                                                                                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                    .lccclooddxxxkkkOOO000OOOOOOkkkkkkOOOkkOOOOOOOOOOOOOO00000000000000000000000000000000000000000OOOOOOOkkkkkxxdddooolllllod                                                                                                                                                                                   " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                    cccllodddxxxkkkOOOOOOOOOOOOOOOkkkkOOOOOOOOOOOOOOOOOOO000000OO00000000000000000000000O00000000OOOOOOOOOkkkkkkxxddoollllllxl                                                                                                                                                                                  " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                   ;ccclodddxxxxxkOOO0OOOOOOOOOOOOOkkkkkkOOOOOOOOOOOOO000000000OOO000OOOOOO00000000000OOOOOOOOOOOOOOOOOOOkkkkkkkxxddollllllllO                                                                                                                                                                                  " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                  '::cloddddxxxxxkkOOO00000OOOOOOOOOOkkkkkOOOOOO000000OOO00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkxxxdoollllclllodk                                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                  ,;:coddddddxxxxkkOOOOOO00OOOOOOOOOOOOOOOOOOOOOOOOO0OOOOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkxxxxddoollllllooox:                                                                                                                                                                                " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                 ,;;clodddddddxxkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkxxxdddoolllllllllo0.                                                                                                                                                                               " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                 ;;:looddddddddxxkkkkkkkOOOOOOOOOOOOOkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkxxxxxxkkkkkxxxxxddoolllllcccld0.                                                                                                                                                                              " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                .::cloodddddddxxxxkkkkkkkkOOOOOOOOkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkOOOOOkkkkkkkxxxxxxxxxxxkkkxxxxddddooollllccccllxK                                                                                                                                                                              " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                ;::coooooooddddxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkOkkkkkkkxxxxxxxxxxxxxxxxddddddoolllccccccccclxk                                                                                                                                                                             " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                .::coooooooodddxxxxxkkkkkkkkkkkkkkkkkxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxddddddoolllcc:::::::clxd                                                                                                                                                                            " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                ;::cloooooooooddxxxxxxxxkkkkkkkkkxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxddddoollccc:::;;;::cclo.                                                                                                                                                                           " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                :;:clooooooooooddddddxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxkkkxxxxxxxxxxxxddddoollcc:::;;;;;:::coOO0XKKKk,                                                                                                                                                                   " | pv -qL 480
sleep 0,020;echo "                                                                                                                                               .:;:cllllloooooooddddddddxxxxxxxxxxxxkkkkkkkkkxxkkkkkkkkkkkkkkOOOOOOOOOOOOOOOkkkkkkkkkkkxxkxxxkkkkkkkxxxxxxxxxdddddooolcc::;;;;;;:::cdO0000OO0:                                                                                                                                                                  " | pv -qL 480
sleep 0,020;echo "                                                                                                                                               .;;:clllllllllooooodddddddddxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkxxxxxxxddddddddoollcc::;;;;;;::cokOOkxddx0                                                                                                                                                                  " | pv -qL 480
sleep 0,020;echo "                                                                                                                                               .:::cclllllllllloooooddddddddddddxxxxxxxxxxxkkkkkkkkkkkkOkkkkkOOOOOOOO000OOOOOOOOkkkkkkkkkkkkkkkkkkxkxxxxxxxdddddxdddooolcc::;;;::::coxxxollodO                                                                                                                                                                  " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                ;:::ccllllllllllloooodddddddddxxxxxxxxxxxxxxkkkkkkkkkkkkkOOOOOOOOO000000OOOOOOOOOOOOOkkOOOkkkkkkkkkkkkxxxxxxxxxxxxxdddollcc:::;;::cloddollllok.                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                 :::ccccccccclllllooooddddddddxxxxxxxxxkkkkkkkkkkkkkkOOOkOOOOOOOOO0000000OOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkxxxxxxxkxxxxxddollc::::::clooodoollloxc                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                 :;;:cccccccccllloooodddddxxxxxkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkxxxxxkkkkkkxxddoolcc::ccclooddddoolloxO                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                 c;;::cccccccccllooooddxxxxxkkkkkOOOOkkkkkkkOOkkkkkkkkkkOOOOOOkkkkOOOOOOOOOOOOOOOOOkkkkkOOOOOOOOOOOkkkkkkxxxkkkkkkkkxxddoolccccllooddddxddoooxO                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                 ';;;:cccccccclllooodddxxxkkkkkkkOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOkkkxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkxxdddollccclllooddddxddoox0                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                 .;,;:cccccccclloooodddxxxxkkkkkkkkkkkkkOOOOkkkkkkkkkkkkkkkkkxxxxkkkkkkkxxxxdddoooooollloooodddddxxxxxxkkkkkkkkkkkkkxxxxddollllllllloooddxdddxO                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                  ',,;:cccccccllooooodddxxxkkkkkkkxkkkkkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxddooollcccccccccclllllllllooooodddxxkkkkkkkkkkkxxxddoolllllllllloddxxddxk                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                   ',;:ccccclllloooddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddddddddddddooollc:::::::::cccclllllllllollllllooddxxkkkkkkkkkxxxxddooooooolllloodxxxdxk.                                                                                                                                                                " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                   .',:cccclllooodddddddddddddddddddddddddxxxxxxdddddddoooooooolllcc:::;;;;;;;:::ccccccclllllllllllllllloodxxxxxxkkxxxxxxddddddxxddooooodxkxdxk.                                                                                                                                                                " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                    .';:ccllloodddddddddddddodooddddddddddddddddddooollllllcccc::::;;;;;;;;;;;;;,,,,,,,,,;;;;::cclllllloddddxxxxkxxxxxxxxddxxxxkkkxdddoodxkxdxk.                                                                                                                                                                " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                     ',:cclooodddddxdddddoooooooooooooolooooooooooollcccccc::::::;;;;;;;;,,,''........'',,,,,,,,;:cllooddddxxxxkkkxxxxxddddxxxxkkkkxddddxxxxxkO.                                                                                                                                                                " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                     ',:ccloodddddooooollllccccccccccccccccclllllloollccc::::::;;;,,,,,,'''.'''......'',:cc::::ccclloodddxxxxkkkkxxxxdddddddxxxxxxxdddxxkkxxxkO                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                      .;llloooolllccccc:::;;;;,,,,,,;;;;;;::::cclooooollcccc::;;,,,''''''''',;:;''''',;:llooddddddddxxxxxkkkkkkkkkxxxxxddddxxxxkxxdddxkOOOOOOOO                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                       ;cllllcc::;;;;;;;;,,,,,'''''''',,,,,,;;:clooddddddollc:;;,,,,,,''',,,;;:::;;::clloddxxxxxxxxkkkkkkkkkkkkkkkkxxxxxxxxxxxxkkxxxxkkkkOOOOO0                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                       .clllc::;;;;;;;;;;,,,,,,''''.......''',;clodxxxxxxxdolc::;;:::;;,,;;;;::::cccllooddddddxxxxxxkkkkkkkkkkkkkkxxxxxxxxxxxxxkkkkkkkkkkkOOOOl                                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                        cllc::;;;;;;;;,,'''..................',:ldxxkkkkkkxdolcccccccc:::::::::cccccclllllloooddxxxxkkxkkkkkkkkkxxxxxxxxxxxxxxkkxkkkOOOOOOOOkx                                                                                                                                                                  " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                        ,llc:;;;;;,''........................',:odxkkkOOOkxdoolllllllllccc::::::::::cccccclloodxxkkkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxkkOOOOOOkkx.                                                                                                                                                                  " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                         llc:;;;;,'....',;;,'.......'''''''',,;coxkkkkOOOkxddoooooooooooooollccccccllllooodddxkkkkkkkOkkkkkkkkkxxxxxddddddddddddxxxxkkkkkxxo.                                                                                                                                                                   " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                         'lcc::;;,'''',,;;::;;,,,,,;;;,,,;;;;;:ldxkkkkOOkkxddddddddddddddddddddddddddxxxxxxxkkkkkkkkkkkkkkkkkxxxxxxxddddddddddddddddoodddo,                                                                                                                                                                     " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                         .lllcc::;;;:::::::::::::::;;;;;;;;:::cldkkkkkOOkkxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkkkxxxxxdddddddddddddddddoc,                                                                                                                                                                          " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                          llllllccccccccccccccc:::;;;;;::ccclccldkkOOOOkkkxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkkOOkkkkkkkkkkkxxxxdddddooooddddddddddo;                                                                                                                                                                           " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                          ;ooooooollllcc:::::::;;;;:::cllllllllldxkOOOOOkkxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOkkkkkkkkkkxxxxxxddddddoooddddddddooo:                                                                                                                                                                           " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                          .ooooooooolccc:::::::::cclllooooollllldxkkOOOOkkxxxxxxxxxxxxdxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkkkkxxxxxxddddddoooooodddoooooo:                                                                                                                                                                           " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                           looooooddoooollllllooooooddoooollllllodxkkOkkkkkxxxxkxxxxdddddooooodddxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddooooodddoooooooc                                                                                                                                                                           " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                           ,olloooodddddxxxddxxdddddddoollllllllodxkkkkkkkkkkkkkkxxxxdoollccclllloodddddddddddddddddddddddddddddddddddoodddddooooooo:                                                                                                                                                                           " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                           .olllloooooddddxxxxxxxxdddoollccccclloddxkkkkkOkkkkkkxxxxxxddoolc::::ccclllloooooooooooooooooddooodddddddddddddoooooooooo:                                                                                                                                                                           " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                            :lllllllooooddddxxdddddooollccc::clloodxxkkkOOkkkkkkkkkkkkxxddoc:::;;:::ccclllllllloooooooooooooooodddddddddddooooooooll:                                                                                                                                                                           " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                            .llllllloooodddddddooooolllccc:::clloodxxkkkkkOOkkkkkkkkkkkkxdoccc::;;;:::cccccclllllllllllloooooooooddddddddooooooollll;                                                                                                                                                                           " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                             :llllllooooooooooooooolllcc:::::cloooddxxkkkkOOOOOOOOOOOOOkxolccccc::;;;;::::cccccccccclllllllooooooooooddddooollllllll:                                                                                                                                                                           " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                              cllllloooooooooooolllllcc:::::clooodddxxxkkkOOOOOkkkkkkxxddlllllllccc:;;;;::::::cccccccclllllooooooooooooooooolllllllll,                                                                                                                                                                          " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                               clllllloollllllllllcccc:::;:cloooodddxxxxxkkkkxxxddoollccccloooooollc::;;;:::::::::ccclllllloooooooooooooooollllllllool;..                                                                                                                                                                       " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                lcccclllllllllcccccc::::;;:clloooodddoooodooollcc:;,,,,;clooooddooolcc::::::::::::cccllllllooooooooooooooollllcccllodolc:;'.                                                                                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                 :ccccccccccccccc:::::;;;;:ccccccclllcccccc:::;''',,;::cllooodddddoollcc:::::::::cccclloooooooooooooooooolllcccclloodddocccccc:,,,'..                                                                                                                                                           " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                  ::::::::::::::::::;;;;;:::c:::;;;;;;;;;;;,,'..',;;:ccllloooddddddooollccccccc::ccclllloooooooooooooolllllcccccllooddddoccccllooddddol;'......                                                                                                                                                 " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                  .c:::::;;:;;;;;;;;;;;;;:::::::;;,,'''''''''...',;::ccllllloooooooooooollccccccccclllllloooooooooooolllllcccccllooodddddocc::lddxxxkkkkkxddoc:;;,,;,'..                                                                                                                                        " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                    :::;;;;;;;;;;;;;;;;;;:::ccc::;;,,'''.'''''''',;;::ccccccclllllllooollllllllcccclooolllooooooooooolllcccccclllooddddxxxocc:,cdxxkkkkkkkkkkkxdlc,'',,;;;,;::cc;,..                                                                                                                            " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                     .::;;;;;;;;;,,,;;;;;::::cc::::;,,,''',,,,,,,,;;::::::c:::::::ccccccllllllllllllooollloooooooooollllccccclllooodddxxxxxocl:,:odxkkkkxxxxxxxxdo:'''',,,,:odxxxkxc;;;,,,'...                                                                                                                  " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                      ,::;;;;;;;;;,;;;;;::::ccc::::;;,,,,,;;:::::::::::::c:::::;;;;;;;:::cclllllllloooollloooooooooolllcccclllllooodddxxxdxdccc;,;codxxxxxxxxxxddo:,'.'',,,:loddxxxl;;;;;;;;;::::;:,'....'.'                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                        ::::::::;;;;;;;:::::::::::;;;;;;;;::cccc:::;;;;;;;;,,,'''''''',,;;:cclllllooooooolloooollllllcccccclllllooodddxxxxxdoclc;,;codddxxxxxxddooc,...',,;codoodddl;;;;;;;;;;;;;;;;;;;cxkxx                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                         :::::::::::;;::::::::::;;;;;;;,,,,,,;;;;;,,'''',,,,,;;;;:cclc:;;,;;::ccllllllllllllllllllllccccccllllllooodddxdxxxxdlllc:;:coddddddddddool:'...''';lddddxxo;;;;,,;;;;;;;;;;;;;:dkxx                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                          :::::::cc:::::::::::;;;;;;,,''''''''''''''',;:cccccclloooddooollc::::cccccccclcclllllclllccccccclllllooooddddddxxxdlllllc:cloddddddddddol:,...',,;:loooddo;;;,,,,,;;;;,,,,,,,;odll                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                           .:::::ccccc:::::;;;,,''......'',,,,,,;;:::cclllccllooooddddddddollcc:::::::ccccccccccccccccccclllllooooodddddddxxdllllllccllodddddddddolc,...'',;::ccllol;;,,,,,,;;;;,,,,;,,;:::d                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                            ;:::::cccccc::;;,,'.'',,;,,,;::ccccclllccccccccllooooooodddddooollcc::::::::ccccccccccc:ccccccclllooooodddddddxxolllllolcllooddddddoool:,...',,;:cllllol;,,,,,,,;;;;;,,,,,,;;col                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                             ;c:::::cccc::;;,'',;::cc::::;;:::::cccc::::ccclllllllloooooooollllccc:::::::::::ccccc::ccccccclloooooddddddddxdocloooollloooodddddooll:;'..'',;:lllllll;,,,,,,,,,,;,,,,;,,,,:dd                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                               c::::::c:::;;;;;:ccccccc::::;:;;;;;;;,,,;;:::cccclllllllooolllllllccccc::::::::::::::::ccccclloooddddddddddddlcloooooolooooooddooolc:;'...',;:clllccc:,,,,,,,,,,,,,,,,,''',lo                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                                 :;;;;;:;;;;;::ccccccc::::;;;,,,''''''',,,;;::cccllllllllooolllllllccc::::::::::::::::::cccloooooddddddddddocloolooooooooodddoooollc;,...',;:cllc;cll;'''''''............;lo                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                            ..,;cl;,,;,,,,,,;;:::cc::::;;;;,,,,,,'''',,,;;:::ccclllllllooolloooolllcc:::;;;;;;::::::::::ccllooooooooodddddolclllcllooloooooooooollcc:,....',;cllc,.:ll:,'''...........';col:                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                   ....',;:,,,,''''',,,,,,,,;;;::::::;;;;;;;;;;;;;;;;:::ccclllllllooooooolllllllllcc:;;;;;;;;;;;;;;::::ccclloooooooooooddolccccccclllllllllloooollcc:,.....',;:cc;...,:ccc::;;;;;;::cccc;'..                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                         ..''.,;:cc::;;,'..........';;,,,,,,,;;;;;;;;;;;;;:::::ccclllllooooddddddoooooolllllllllccc:;;;;;;;;;;;;;;;:::ccclllooooooooooooolccccc:::loooooooolloollccc:;'....',;;::;'.......',,,,,,,''........                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                  ...';;;;;;,,,,'''............,:cccllc,,',,,,,,;;;;;;;::::cclllooooooooodddddddddooolllllllllcccc:;;,,,,,,,,,,,;;;::cccllloooooooooooollccccc::::clllclllooooolc:::;,'.....';:ccc:;,'....................''                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                              .,;;;,,,,,,,''''''.....     .';looooloool;,''',,,;;;;;::::cclllooooooooooooooooooooooollllllllccc:::;;,,,,,,,,,,,,;;;::cclllllllooooooooolcccccc:::clollccccccllllcc:::,'.....',;:clllc:;'................''''                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                         ..''''''''''''''............ ..,codddddddddolc;,''''',,,;;;;::cccllllllllllllccclllllllllcccccccccc::::;;,,,,,,,,,,,,,;;:::ccllllllllloollllllcccccc::::lloollccllllccccccc:,''....',;:cllllcc;'............'''''''                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                     ....'''''''''''''..............';loddddddxxxxdooc:;,''....'',,;;;::cccccccccccccc::::::cccc::cc::::::::;;;;,,,,,,,,,,,,,;;;::cccllllllllllllllllllccccc::c:clooolllcllllllcc:::;,,'....',;;:clllllc,''........'''''''''                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                               .........''''''''...''............,:ldddddddddxxddoollcc::;;'......',,;;;;::;::::::::::;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,;;;;::ccccllllllllllllllloddlcccc:ccccllooolllllllllcccc:;,,'....'',;;cllllll:''''''''..'''''''''                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                           ...............'''..''..'...........;looddddddddddddoollllllllcc;'......',,,,;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,''''',,,,,,;;;;::ccccccclllllllllllloxkxocccc::ccccloooollllllllllccc::;,'.....',,;:cllolll;''''''''''''''''''                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                        .;'..'...............'...............;cloooooooooooooooooolllooooolc;,'..'',,,'::;,,,,,,,,,,,',,,,'',,,,,'',,,,,,,'''''''',,,,,,,;;::::ccccccllllllllllloxkkxocccc::cccclloooolllllllollllcc:;,,'.....',,;:clllll:''''''''''''''''''                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                     'll:.....''..........................',:clllolllclollllllcccllllllooolc:;,,,,,,,'.odoc;,,,,'''''''''''''''''''''''''''''''''',,,,,;;;;:::ccccccclllllllllodxkkxdlccc::ccccclloooolllllloooollcc::;,,'....'',,:ccllllc,'''''''''''''''''                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                   :lol;.....''....................... ..;::ccclllcccllllllccc:clllclllooolc:;;;;;;;'..lddolc:;;,''''''''''''''''''''''''''''',,,'',,,;;;:::::ccccccccccccclllooddoolcccc:cccccclloooollllllooollllcc:;;,,'....',,;cllllll:'''''''''''''''''                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                              .;loollc,....'''.........''..............,;:cccllllcclllllcccccccllcccllodolc:;;:::;:;...lodoolc:;,,,'''''''...''''''''''''''''',,,,,,;;;::::::cccccccccccclodddddoolccccc::cccccclloooolllllooooollllc:::;;,'....',,;clllllc,''''''''''''''''                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                          .cdoooolccc;....''...........'.'''.........';::cclllllllooooollllloooooooddddolc:::::::::'. .coooolc:;,,',,,,''''''''''''...''''''',,,,,,;;;;:::::cccccccccclloddxxdddddolccc::ccccccclooooolllllooooollllcc::::;,.....',,:clllll:''''''''''''''''                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                         cdooooolc:c:...................''......  ..,;::ccllllloooooooooooooooodddxxxdlcc::::cc:::,.   ':lolcccc:;,'',,,,,,,,'''''''''''''',,,,,,;;;;;:::::::cc:ccclooddddddddddollccc::cccccccllooooolllloooooollllcccccc:,.....''';:cllllc;'''''''''''''''                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                       :loooollc::c:'....................'...... ..,;::cclllllloooooooooooooodddxxxxolccc:cccc:c:,..   .'colloollc:;''',,,,,,,,,,,'''','',,,,,,;;;;;;:::::::ccclodxxdddxxxxxxxxddocclc::ccllccclloooooollloooooollllccccccc;'.....'',;ccllclc,'''''''...'''.                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                     ,olooolllc::c:,....................''..... ..,;::cccllllllooooooooooooodddxxxdolccccccccc:c;... ...,cooodooollc:;,''',,,,,,,,,,,,,,,,,,,;;;;;;:::::::cclodxxkkkkkkkkkkOOkkxdoccc::ccllcccclooooooollooooooolllllcccccc:,......'',:clllcc;''''..........                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .oollllllc:::c:............'.......''..... ..,;;::ccllllllllloooooooooodddxxxdolcccccclcc:c:'......,;:ooodddooollc:;,,,,,,,,,,,,;;;,;;;;;;;:::::::cclloddxxxxkkkkOOOOOOOOkxoccclc::cclllccllooodoolllooooooooollllllllc:;'.......',;ccccc:,''...........                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .lollllcc:::::.....................'..... ..';;::ccclllllllllloooooooooddxxdollcccccclcc::c,....';;;;:looddddoooollcc::;;;;,,,;;;;;;;;;;;:::::cclloooodxxxxxkkkkkkkkkkxdl:;,,:cc:::cllllllllooddoooolooooooooollllllllc:;,........',;:::::;'............                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .cllllcc:cccc,.......''...........'..... ..',;::ccclllllllllllooooooooddxddolcc:ccccllc:cc;....';ccc:ccoddddddddoollcc::;;;:::::ccccccc::ccloooooolccloooddddddxxxkxxoc:;;;::ccc:ccllllllllooodddooolooooooooollllllllc::,'........',;;;;,,'............                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .llllcc:cccc;.......''.................  .',;:::cccclllllllllooooooooddddolcc:::cclllc::c:,....,:loolcccodddddddoolcc:,'''';cllcccccclllooddxxxdoc;;cccccllllllllcc::;;;;:::ccccclllllllllloooddoooollooooooollllllllllc:;,'........',,,,;;,............                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .lllccclllcc......'''.................. ..,;;::cccccclllllllloooooooddddolc:::ccclllcc:c:,...';cooddocclllddddddolc:,'....',;:llooooooooolllllc::cccllcccccccllccc:::;:::::ccccclloooolllllooodddooooooooooooolllooolllc:;,''......','',;:::;'..........                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .cllllloolc......''''................. ..,;:::ccclcclllllllllooooooddddolcc::cccllllc:cc;'..';coooooodolllloxxdoc:,..,;;;;;;ccc:;::c::;,,,,,,''',:oxkxdooooooooooollcccccccccccllooooolllloooddddoooooooooooooooooooollc::;,,'.......,,;;::::;'.........                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .cllooooolc.....''''.................  .';:::ccclllllllllllloooooooddollc:::cccllolc::c:,...,cloddxxkkdollllodoc;...';:ccclcc:::;,;::;'...',,;;;;;:oxkkxxxxxxxxxxxxxddddoolllcllooooolllllooddddooooooooooooooooooooollcc:;;,,'......',;;;;;;;,.........                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .clooloolo'....''''.................. ..,:::ccccllllllllllloooooodddolccc:ccclllolc::cc;'...,ldxkkkkkkkdolll::;'...',:clllllllolc::::;,,,;:cccc:::;:lxkkkkxxxxxxxxxxxxxxdoolccllooolllllllooddddooooooooooooooooooooollcc::;;;,'....',;;::::::;'........                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .llooooloc...'''''.................. ..,;::cccclllllllllllloooooodoolcc::cclllooolcccc:,....;dxkkOOOOOkkdlc;,,''''',:llolllloddddlc::;;::lllllllcc::;cllooddddddddxxxddolllllcllooollcclloodddddooooooooooooooooooooollcc::::;;,.....',;:::::::;'.......                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .llooolol....'''...................  .';::ccccllllllllllllloooooooollccccclllooolccccc;'...,cdkkOOOOOOkko:,,,,,,,,;:looooolodxxxxdlccccclodooooollcc:::cccllllllllllllcclllllloooolllcclloodddddoooooooooooooooooooooollcc:::::;'.....',;;:::::;,.......                                                                                                    " | pv -qL 420
sleep 0,020;echo "                                                                                                    .looolol'.....'...................  ..,::ccccllllllllllllloooooooollccccllloooolccccc:,...,:coxkOOOOOkdl:,,,;;::;::coodoolccodddolcc::ccoddddddooollccc:::cclllllllllcclllllllooooolllllloodddddoooooooooooooooooooooollccccc::;,......',;;;;;;;;'......                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .ooooll:...'.'...................   .';:ccccllllllllllllllollloolllcccclllooooolccll:,..',;clloxkkOkdl;,,;;:ccc::::coooodlcoddddoc:::::loooooooooolllllccc::clodxxxxddooollllooodooolllloooddddddooooooooooooooooooooollllcccc:;,'.....',,;;;:::;;'.....                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .lollcc.........................   ..,;:ccccllllllllllllloolloolllcccclllooooolccclc:'..,:cllloodxdl;,,,;;::cc:;;;;clloodddkkkkkxolllloxxxxxxxxxddooooolllcc:;;coxxxxdoollloooooddooollooooddddddoooooooooooooooooooooollllllcc:;,'.....',,;;::::;,'....                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .lllc:;........'...............    .',;:cccclllllllllllloollloollcccclloooodollcclc:,'.';coooooocc:,,,;::cllllc:::coddddxdkOOOOkxdddodxkOOOOOOOOkkkxxxxxxxddl::;:llodooooolloooodooollllooodddddoooooooooooooodddddooooollllllc::;,'.....',,;;::::;,....                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .llc::'......''................   ...,;:::cclllllllllllloolloolllccllloooooollccllc;,..,:ldxxdlc;;::cllodddxxolllodxxxxxxxkOOOOkdddddxOOOOOOOOOOOkkkkkkkkkkxooooddoolllollllllooooolllllllooddddoooooooooooooodddddooooooooollcc:;;,'.....'''',,;;;;,...                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .cc::,......'''...............    ..',;:::::cccccccclllllllllllcccclloooooollcccll:;'.',:odxkdc;;:loddxxxxxxxoooodxkkxxxxkOOOOOxdddddkO0000OOOOOOkOOOOOOOkkdooodxxddololllcccllllccc::clccllllllllllloooloooooddddooooooooooollcc:;;;'.....''',''',,,'..                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .c:::......'''...............     ..',;;;;::ccccccccccclcclllccc:cclllllllccccclll:,''';coxxdl;;codxxxkkkkkkdooooxkkkxdxxOO00OkxddddxOO000000OOOOOOOOOOOOOkddddxxxxdlllcclc:cllllccc:clloooolllllcccccclllllllooooooolloooooollccc:::;.....'',,;;;,,,'..                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                    .c:c,..''.'''................     ..',,;;;:::::::ccccccccccllc:c::llllllllllccclll:,'',:ldddl;,:odxkkkkkkkkkdooodxkkkxxdxO00OOxxdddxkO0000000OOOOOOOOOOOOkxdddxkkxdolllcccc:cclllccc:ccllloollloolllllccc:::cclllooollllllclccccccccc;'.....'',,;;;;,,'.                                                                                                    " | pv -qL 480
sleep 0,020;echo "                                                                                                                                                                                                                                                                                                                                                                                                                                                                " | pv -qL 480
